title: My Hexo Blog
subtitle: A blog powered by Hexo
description: This is a sample Hexo blog.
author: Your Name
language: en
timezone: Asia/Shanghai
url: https://yourdomain.com
root: /
permalink: :year/:month/:day/:title/
# theme: landscape
theme: flexy

# Deployment
deploy:
  type: git
  repo: https://github.com/yourusername/your-repo.git
  branch: gh-pages

# Extensions
# Add any additional plugins or settings here.